### ISSUE TITLE
Can't compile minified version of Firebase module

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t1-runtime#163]
See the code to compile below. The error I'm seeing is:

```
>> colony app.js
fs.js:1740
  fs.writeSync(this.fd, data, 0, data.length);
                                     ^
TypeError: Cannot read property 'length' of undefined
    at SyncWriteStream.write (fs.js:1740:38)
    at /Users/Jon/Work/technical/colony-compiler/bin/colony-compiler.js:47:22
    at Object.exports.compile (/Users/Jon/Work/technical/colony-compiler/src/bytecode/index.js:21:7)
    at Object.exports.toBytecode (/Users/Jon/Work/technical/colony-compiler/src/index.js:29:12)
    at cli (/Users/Jon/Work/technical/colony-compiler/bin/colony-compiler.js:46:12)
    at Object.<anonymous> (/Users/Jon/Work/technical/colony-compiler/bin/colony-compiler.js:55:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

You can get the code with `npm install firebase` and app.js just contains:

``` .js
var fb = require('firebase');
```

**Comment by mettasmartware** [comment]
+1 for getting firebase to work with Tessel. It'd be awesome if all the rapid prototyping tools could play nice together!
